feat: run against higher order k8s kinds
kubewarden/capabilities-psp-policy pull request #39
Opened 2023-05-05 13:11 UTC by KhaledEmaraDev

## Description

Fix #27

## Test

To test this pull request, you can run the following commands:

## Additional Information

### Tradeoff

### Potential improvement

2023-05-05 18:49 UTC, jvanz requested changes

2023-05-23 17:38 UTC, jvanz requested changes

2023-05-24 11:54 UTC, jvanz commented on src/validate.rs
> +fn get_caps(pod_spec: &PodSpec) -> Result<HashSet<String>> {
Yes, that was what I was trying to say. :)

2023-05-24 13:28 UTC, KhaledEmaraDev commented on src/validate.rs
> +fn get_caps(pod_spec: &PodSpec) -> Result<HashSet<String>> {
@jvanz Done. :)

2023-05-25 08:36 UTC, viccuad requested changes
LGTM (some linter errors, also missing commiting artifacthub-pkg.yml to history)

Yet, is there a specific reason why we don't validate ephemeral containers? I cannot recall one, they have a securityContext, hence we can set capabilities for them (and an attacker can use it for privilege escalation). I suppose it's because the policy predates their inclusion and the analogous PSP didn't do it either for the same reason.

I would take that line from the readme (or add the reason if there's any), and open an issue to check for caps on ephemeral containers.

2023-05-26 09:54 UTC, viccuad approved these changes
Approving, I'm ok merging as it is. Still needs linters fixes, please fix those.

Opened https://github.com/kubewarden/capabilities-psp-policy/issues/41 to also check ephemeral containers.

2023-05-26 12:10 UTC, jvanz commented
> Approving, I'm ok merging as it is. Still needs linters fixes, please fix those.

@KhaledEmaraDev, please do it.

2023-05-26 13:12 UTC, KhaledEmaraDev commented
@jvanz @viccuad Done.

2023-05-26 16:30 UTC, jvanz approved these changes

2023-05-29 13:14 UTC, merged